In [1]:
import pandas as pd 

df = pd.read_csv("../data/fraudTrain.csv")

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [2]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  str
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  str
 4   category               1296675 non-null  str
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  str
 7   last                   1296675 non-null  str
 8   gender                 1296675 non-null  str
 9   street                 1296675 non-null  str
 10  city                   1296675 non-null  str
 11  state                  1296675 non-null  str
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  str
 17  dob                    1296675 non-null  str
 18  trans_num              1296675 non-null  str
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), str(12)
memory usage: 227.5 MB

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [3]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

Drop useless / index columns

In [4]:
df = df.drop(columns=["Unnamed: 0"])

Convert dates

In [5]:
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])
df["dob"] = pd.to_datetime(df["dob"])

Create useful time features

In [6]:
df["transaction_hour"] = df["trans_date_trans_time"].dt.hour
df["transaction_day"] = df["trans_date_trans_time"].dt.day
df["transaction_month"] = df["trans_date_trans_time"].dt.month
df["transaction_dayofweek"] = df["trans_date_trans_time"].dt.dayofweek

Create age feature

In [7]:
df["age"] = (
    df["trans_date_trans_time"].dt.year - df["dob"].dt.year
)

Create Distance feature, 
Fraud may depend on distancebetween user location and merchant location.

In [8]:
import numpy as np

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371 # Earth radius in kilometers
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

df["distance_km"] = haversine_distance(
    df["lat"], df["long"], df["merch_lat"], df["merch_long"]
)

Analyze fraud by category

In [9]:
df.groupby("category")["is_fraud"].mean().sort_values(ascending=False)

category
shopping_net      0.017561
misc_net          0.014458
grocery_pos       0.014098
shopping_pos      0.007225
gas_transport     0.004694
misc_pos          0.003139
grocery_net       0.002948
travel            0.002864
entertainment     0.002478
personal_care     0.002424
kids_pets         0.002114
food_dining       0.001651
home              0.001608
health_fitness    0.001549
Name: is_fraud, dtype: float64

Analyze fraud by amount

In [10]:
df.groupby("is_fraud")["amt"].describe()

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,1289169.0,67.667110,154.007971,1.00,9.6100,47.280,82.540,28948.90
1,7506.0,531.320092,390.560070,1.06,245.6625,396.505,900.875,1376.04

Analyze fraud by hour

In [11]:
df.groupby("transaction_hour")["is_fraud"].mean().sort_values(ascending=False)

transaction_hour
22    0.028829
23    0.028374
1     0.015349
0     0.014940
2     0.014652
3     0.014239
5     0.001423
7     0.001327
14    0.001325
19    0.001236
18    0.001226
13    0.001225
15    0.001208
17    0.001192
16    0.001156
8     0.001153
21    0.001129
9     0.001114
4     0.001099
12    0.001027
11    0.000998
20    0.000952
10    0.000946
6     0.000946
Name: is_fraud, dtype: float64

Columns to remove before ML:
these leak identity or are not directly useful for baseline ML

In [12]:
drop_cols = [
    "trans_date_trans_time", "cc_num",
    "first", "last", "street", "city",
    "state", "zip", "dob", "trans_num",
    "unix_time", "merchant", "lat",
    "long", "merch_lat", "merch_long"
]

In [13]:
model_df = df.drop(columns = drop_cols)

Save processed Dataset

In [14]:
model_df.to_csv("../data/processed_fraud_dataset.csv", index=False)

Completion Checkpoint

In [15]:
model_df.head()
model_df.info()
model_df["is_fraud"].value_counts(normalize=True) * 100

<class 'pandas.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 12 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   category               1296675 non-null  str
 1   amt                    1296675 non-null  float64
 2   gender                 1296675 non-null  str
 3   city_pop               1296675 non-null  int64
 4   job                    1296675 non-null  str
 5   is_fraud               1296675 non-null  int64
 6   transaction_hour       1296675 non-null  int32
 7   transaction_day        1296675 non-null  int32
 8   transaction_month      1296675 non-null  int32
 9   transaction_dayofweek  1296675 non-null  int32
 10  age                    1296675 non-null  int32
 11  distance_km            1296675 non-null  float64
dtypes: float64(2), int32(5), int64(2), str(3)
memory usage: 94.0 MB

is_fraud
0    99.421135
1     0.578865
Name: proportion, dtype: float64